# Generated by Django 5.0.1 on 2024-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgolangversion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupgolangversion',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
