# Generated by Django 5.0.1 on 2024-01-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0002_alter_groupgolangversion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorgolangversion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='mango_api.groupgolangversion'),
        ),
    ]
