# Generated by Django 5.0.1 on 2024-01-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0003_alter_operatorgolangversion_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorgolangversion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
