# Generated by Django 5.0.1 on 2024-01-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0004_alter_operatorgolangversion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorgolangversion',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
