# Generated by Django 5.0.1 on 2024-02-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0006_alter_distributionschemagolangversion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistorygolangversion',
            name='date_time_postupil',
            field=models.DateTimeField(null=True),
        ),
    ]
