# Generated by Django 5.0.1 on 2024-02-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0007_callhistorygolangversion_date_time_postupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistorygolangversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
