# Generated by Django 5.0.1 on 2024-02-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0008_alter_callhistorygolangversion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistorygolangversion',
            name='entry_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
