# Generated by Django 5.0.1 on 2024-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_api', '0010_alter_callhistorygolangversion_recording_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecordinggolangversion',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
